name: "🐞 Сообщить об ошибке"
description: Нашли ошибку или неточность в наших материалах? Вам сюда
title: Ошибка в ...
labels: ["ошибка"]
body:
  - type: input
    id: link-to-the-article
    attributes:
      label: Ссылка на статью
      description: Вставьте адрес или название статьи с ошибкой.
      placeholder: "https://doka.guide/"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Описание
      description: Опишите, в чём ошибка или неточность. Приложите скрин, если это нужно.
    validations:
      required: true
  - type: textarea
    id: proofs
    attributes:
      label: Пруфы
      description: Дайте ссылки на материалы с верной информацией для честного фактчекинга.
