name: "📝 Предложить идею материала"
description: Если вы не нашли статью или доку по нужной теме и считаете, что такой материал нужен
title: Не хватает материала о ...
body:
  - type: textarea
    id: description
    attributes:
      label: Тема
      description: Коротко опишите тему, которая не освещена. Какая информация должна быть в материале?
    validations:
      required: true
  - type: textarea
    id: proofs
    attributes:
      label: Зачем
      description: Расскажите, почему эта тема важна, насколько она востребована.
    validations:
      required: true
  - type: checkboxes
    id: i-will-handle-it
    attributes:
      label: Кто напишет материал
      description: Поставьте галочку, если готовы написать этот материал сами. Мы поможем вам в этом.
      options:
        - label: Я сам напишу этот материал
