name: "❓ Предложить идею вопроса для рубрики «На собеседовании»"
description: Если не нашли вопроса для рубрики «На собеседовании» и считаете, что он нужен
title: Добавить ответ на вопрос: ...
body:
  - type: textarea
    id: description
    attributes:
      label: Вопрос
      description: Опишите подробнее вопрос для рубрики «На собеседовании»
    validations:
      required: true
  - type: checkboxes
    id: i-will-handle-it
    attributes:
      label: Кто ответит на вопрос
      description: Поставьте галочку, если готовы написать этот материал сами. Мы поможем вам в этом.
      options:
        - label: Я сам(а) напишу этот материал
