name: EditorConfig All

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - id: files
        uses: Ana06/get-changed-files@v1.2
      - name: Проверка линтером
        run: npх editorconfig-checker
