name: Frontmatter

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - id: files
        if: ${{ github.event_name == 'pull_request' }}
        uses: Ana06/get-changed-files@v1.2
        with:
          filter: 'index.md'
      - name: Проверка линтером в PR
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          files="${{ steps.files.outputs.all }}"
          if ! [[ $files == "" ]]; then
            echo "Проверка для файлов из PR"
            npx yaml-cat -f json ${{ steps.files.outputs.all }} -o result.json
            node .github/scripts/frontmatter.js
          else
            echo "В PR нет файлов для проверки"
          fi
      - name: Проверка линтером в main
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "Проверка для всех файлов"
          npx yaml-cat -f json **/**/index.md -o result.json
          node .github/scripts/frontmatter.js
