name: Link Checker PR

on:
  workflow_run:
    workflows:
      - "Frontmatter Check"
    types:
      - completed

jobs:
  markdown-link-check:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: files
        uses: Ana06/get-changed-files@v1.2
        with:
          filter: '*.md'
          format: 'csv'
      - name: Проверка ссылок в PR
        if: ${{ steps.files.outputs.all != '' }}
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: ${{ steps.files.outputs.all }}
          markdown: true
          serverRoot: "/home/runner/work/content/content"
          linksToSkip: "https?://(localhost|codepen.io)?(:[0-9]+)?/.*"
