name: Link Checker All

on:
  schedule:
    - cron: '0 6 * * 5'

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Проверка ссылок в исходниках
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "**/*.md"
          markdown: true
          linksToSkip: "https?://(localhost|codepen.io)?(:[0-9]+)?/.*"
      - name: Проверка ссылок в собранном сайте
        uses: ruzickap/action-my-broken-link-checker@v2.2.4
        with:
          url: https://doka.guide
          cmd_params: --buffer-size=8192 --max-connections=10 --color=always --skip-tls-verification --limit-redirections=5 --timeout=20
          run_timeout: 600
