name: Link Checker All

on:
  schedule:
    - cron: '0 6 * * 5'

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Проверка ссылок в собранном сайте
        uses: ruzickap/action-my-broken-link-checker@v2.2.5
        with:
          url: https://doka.guide
          cmd_params: --buffer-size=8192 --max-connections=10 --color=always --skip-tls-verification --timeout=20 --exclude=^https?:\/\/(localhost|127\.0\.0\.1|codepen.io)?(:[0-9]+)?(\/.*)?
          run_timeout: 600
