name: Link Checker PR

on:
  pull_request

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: files
        if: ${{ github.event_name == 'pull_request' }}
        uses: Ana06/get-changed-files@v1.2
        with:
          filter: '*.md'
          format: 'csv'
      - name: Проверка ссылок в PR
        if: ${{ steps.files.outputs.all != '' }}
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: ${{ steps.files.outputs.all }}
          markdown: true
          serverRoot: "/home/runner/work/content/content"
          linksToSkip: "https?://(localhost|codepen.io)?/.*"
