name: PR Preview

on:
  pull_request_target:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.files.outputs.all }}
    steps:
      - name: Выборка файлов для формирования списка
        id: files
        run: |
          pr_files=$(echo $(curl \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files))
          list=$(echo $pr_files | grep -o '"filename": "[^"]*' | cut -d'"' -f4)
          echo "::set-output name=all::$list"
          echo $list
  surge-preview:
    runs-on: ubuntu-latest
    needs:
      - prepare
    env:
      DEPLOY_DOMAIN: 'https://${{ github.repository_owner }}-content-pr-${{ github.event.pull_request.number }}.surge.sh'
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
    steps:
      - name: Загрузка platform
        uses: actions/checkout@v2
        with:
          repository: doka-guide/platform
      - name: Загрузка контента
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.after }}
          path: content
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Кэширование модулей
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Установка модулей
        run: npm ci
      - name: Сообщение о начале публикации превью
        uses: hasura/comment-progress@v2.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.pull_request.number }}
          id: surge-progress-${{ github.event.pull_request.number }}
          message: 'Идёт сборка и публикация превью... [Подробнее](https://github.com/${{ github.repository }}/runs/${{ github.run_id }}?check_suite_focus=true)'
          recreate: true
      - name: Форматирование списка файлов
        id: links
        run: |
          file_list=''
          for changed_file in ${{ needs.prepare.outputs.files }}; do
            replace='html'
            if ! [[ $changed_file == '' ]]; then
              page=$(echo "${changed_file/md/$replace}")
              file_list=$(echo -e "${file_list}<li><a href="${{ env.DEPLOY_DOMAIN }}/${page}">${changed_file}</a></li>")
            fi
          done
          if ! [[ $file_list == '' ]]; then
            file_list=$(echo -e "<br><hr><p>Список ссылок на материалы:<ul>${file_list}</ul><p>")
          fi
          echo ::set-output name=list::$(echo -e "${file_list}")
      - name: Сборка и публикация сайта
        id: surge
        continue-on-error: true
        run: |
          node make-links.js --default
          npm run preview
          if ! [[ ${{ env.SURGE_TOKEN == '' }} ]]; then
            npx surge ./dist ${{ env.DEPLOY_DOMAIN }} --token ${{ env.SURGE_TOKEN }}
          else
            echo 'Публикация для форка репозитория'
            npx surge ./dist ${{ env.DEPLOY_DOMAIN }} --token '6973bdb764f0d5fd07c910de27e2d7d0'
          fi
          echo 'Ссылка на превью — ${{ env.DEPLOY_DOMAIN }}'
          echo -e "${{ steps.links.outputs.list }}"
      - name: Сообщение о неудаче публикации превью
        uses: hasura/comment-progress@v2.1.0
        if: failure()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.pull_request.number }}
          id: surge-progress-${{ github.event.pull_request.number }}
          message: 'Превью контента из ${{ github.event.after }} не опубликовано. Ошибка сборки или публикации. [Подробнее](https://github.com/${{ github.repository }}/runs/${{ steps.check.outputs.check_id }}?check_suite_focus=true)'
          fail: true
          recreate: true
      - name: Сообщение об успехе публикации превью
        uses: hasura/comment-progress@v2.1.0
        if: success()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.pull_request.number }}
          id: surge-progress-${{ github.event.pull_request.number }}
          message: '<details><summary><a href="${{ env.DEPLOY_DOMAIN }}">Превью контента</a> из ${{ github.event.after }} опубликовано.</summary>${{ steps.links.outputs.list }}</details>'
          recreate: true
