name: Spell and Grammar Check

on:
  pull_request:
    branches: [ main ]

jobs:
  check_spelling_and_grammar:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai

    - name: Check spelling and grammar
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python spellCheckAI.py ${{ github.event.pull_request.number }}
