name: Update Index

on:
  workflow_run:
    workflows:
      - EditorConfig
    branches:
      - main
    types:
      - completed

jobs:
  update-index:
    runs-on: ubuntu-latest
    if: $ {{ github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.DOKA_BOT_ACCESS_TOKEN }}
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Правка полей updatedAt и createdAt
        run: node .github/scripts/update-index.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Правит поля updatedAt и createdAt
          file_pattern: ./**/index.11tydata.json
          commit_user_name: Doka Dog
          commit_user_email: hi@doka.guide
          commit_author: Doka Dog <hi@doka.guide>
