name: YaSpeller Main

on:
  workflow_dispatch:
    inputs:
      message:
        required: true
        description: "YaSpeller Test"

  workflow_run:
    workflows:
      - EditorConfig
    types:
      - completed

jobs:
  spell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Проверка правописания
        run: npx yaspeller --only-errors --file-extensions ".md,.html" *
